/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yfsd_wl_jnibsdiff_bsdiff_BSDiffUtils */

#ifndef _Included_com_yfsd_wl_jnibsdiff_bsdiff_BSDiffUtils
#define _Included_com_yfsd_wl_jnibsdiff_bsdiff_BSDiffUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yfsd_wl_jnibsdiff_bsdiff_BSDiffUtils
 * Method:    bsPatch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_yfsd_wl_jnibsdiff_bsdiff_BSDiffUtils_bsPatch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
