/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include<com_yfsd_wl_jnibsdiff_bsdiff_BSDiffUtils.h>

/* Header for class com_yfsd_wl_jnibsdiff_bsdiff_BSDiffUtils */

#ifdef __cplusplus

extern "C" {
#endif
/*
 * Class:     com_yfsd_wl_jnibsdiff_bsdiff_BSDiffUtils
 * Method:    bsPatch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_yfsd_wl_jnibsdiff_bsdiff_BSDiffUtils_bsPatch
  (JNIEnv * env, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
/*
 * Class:     com_yfsd_wl_jnibsdiff_bsdiff_BSDiffUtils
 * Method:    bsPatch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */

 extern "C"{
 extern  int p_main(int argc,char * argv[]);
 }
 extern "C"
JNIEXPORT void JNICALL Java_com_yfsd_wl_jnibsdiff_bsdiff_BSDiffUtils_bsPatch(JNIEnv *env, jclass jclass, jstring oldApk_,
                                                                             jstring patch_, jstring output_){
   //将java字符串转为c/c++ 的字符串  或者说 转换为utf-8的char指针
      const char *oldApk = env->GetStringUTFChars(oldApk_, 0);
      const char *patch = env->GetStringUTFChars(patch_, 0);
      const char *output = env->GetStringUTFChars(output_, 0);
      //bspatch oldfile newfile patchfile
      const char *argv[] = {"",oldApk,output,patch};
      p_main(4, (char **)argv);
      // 释放只想unicode格式的char指针
      env->ReleaseStringUTFChars(oldApk_, oldApk);
      env->ReleaseStringUTFChars(patch_, patch);
      env->ReleaseStringUTFChars(output_, output);
  };
